batch_size: 8
epoch: 200
learning_rate: 1e-3 #1e-4 with menghao
gpu: 0
num_point: 2560
optimizer: Adam
weight_decay: 1e-4
normal: True
num_class: 3
contin: False
uniform: True
debug: False
eval_only: False

defaults:
  - model: Hengshuang

hydra:
  run:
    dir: log/cls/${model.name}

  sweep:
    dir: log/cls
    subdir: ${model.name}
